//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogr_Kayit_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrMail { get; set; }
        public string OgrFotograf { get; set; }
        public string OgrAdres { get; set; }
        public Nullable<int> OgrYas { get; set; }
        public Nullable<int> OgrSınıf { get; set; }
        public Nullable<int> OgrNot { get; set; }
        public string OgrHarfNotu { get; set; }
    }
}
